<a href="https://colab.research.google.com/github/darkhorse1998/SHALA2020/blob/master/Copy_of_Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [18]:
import numpy as np
np.random.seed(64)

a = np.random.randn(3,5)*100
b = np.random.randn(3,5)*100
print(a)
print(b)

[[ 110.03229392 -198.26274166 -115.02495131  219.29163627 -190.14350266]
 [ -43.38966946 -113.55818657 -103.32950701 -237.19586221   70.33380865]
 [  38.48421246  175.04858048 -119.50692575   29.51276814    4.83208849]]
[[ -17.12988524  -50.50270277 -136.85140319  -10.25786888  -38.65773297]
 [ -45.61057624 -135.9171708   -39.68769853   59.46319066 -137.7933694 ]
 [  51.1795035   -54.13323871  -49.09407605   32.61542225   73.86735916]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [25]:
c = np.random.randint(1,100,size=(100,))
d = np.zeros((3,3))
print(c)
print(d)

[72 33 42 83 43 90 25 68 59 63 23 17 45 68 35 94 81 22 64  2 44 17 47 40
 14 16 49 37 78 26 18 44 62 44  6 98 75 36 37 72 49 49 61 50 17 32 69  7
 35 87 70 10 52  1 34 73 30 33  7 69 89 18 75 83 24 91 19 25 45 38 85 27
 12  9 72 68 67 10 93 47 82 41 57  6 98 79 12 37 35 69  4  2 37  2 28 78
 92 68 87 89]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [21]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [22]:
f = np.ones((5,5))
g = np.eye(5)
print(f)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [33]:
h = c.reshape((10,10))
c1 = h.flatten()
if(c.shape == c1.shape):
  print("YES")
else:
  print("NO")

YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [35]:
A = np.random.rand(2,10,5)
A = A.reshape(5,2,10)
print(A)

[[[0.22962989 0.93128459 0.84469673 0.19869428 0.05590165 0.47183167
   0.87196831 0.40113814 0.35498085 0.16834766]
  [0.44483561 0.57398082 0.85509222 0.94830422 0.59879882 0.89521894
   0.25210234 0.28324278 0.34920544 0.62615601]]

 [[0.67083096 0.4979284  0.91419001 0.78628947 0.38979661 0.40450823
   0.11881165 0.24100343 0.53744136 0.20710271]
  [0.87422053 0.94610908 0.13455216 0.07074243 0.51551924 0.62223359
   0.97097787 0.6211999  0.4400663  0.51800519]]

 [[0.99825443 0.57792125 0.07243548 0.28645383 0.78237621 0.67161929
   0.92358405 0.19916519 0.63864741 0.93294711]
  [0.30519689 0.54188208 0.8028703  0.28720456 0.16961143 0.18364317
   0.29498396 0.16159882 0.18036664 0.79821427]]

 [[0.5356511  0.12859598 0.77478947 0.14291007 0.85121081 0.54835242
   0.31259253 0.29961732 0.67666334 0.34329742]
  [0.59408845 0.94103195 0.82974189 0.05333369 0.8265587  0.6443379
   0.09796639 0.00843636 0.82194    0.95427482]]

 [[0.61115249 0.8686227  0.80107624 0.40372932 0.48771927

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [38]:
np.random.seed(0)
X = np.random.rand(10,5)
print("Matrix X is: \n{}".format(X))
print("\n")
print(X.min(axis=0),X.argmin(axis=0))
print(X.max(axis=0),X.argmin(axis=0))
print(X.min(axis=1),X.argmin(axis=1))
print(X.max(axis=1),X.argmin(axis=1))
print(X.max(),X.argmax())


Matrix X is: 
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]


[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] [3 3 9 8 6]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] [3 3 9 8 6]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] [4 4 4 1 4 1 4 1 3 2]
[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787] [4 4 4 1 4 1 4 1 

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)




## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.